template:
  params:
    bootswatch: sandstone

authors:
  Gabriel Carrasco-Escobar:
    href: https://twitter.com/Gabc91

navbar:
  type: default
  left:
  - icon: fa-home fa-lg
    href: index.html
  - text: Codes
    menu:
    - text: An Introduction to ggdag
      href: /articles/intro-to-ggdag.html
    - text: An Introduction to DAGs
      href: /articles/intro-to-dags.html
    - text: Common Structures of Bias
      href: /articles/bias-structures.html
